In [50]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [51]:
df = pd.read_csv('../__datasets__/train.csv')[['Age', 'Pclass', 'SibSp', 'Parch', 'Survived']]

In [52]:
df.sample(4)

      Age  Pclass  SibSp  Parch  Survived
782  29.0       1      0      0         0
699  42.0       3      0      0         0
178  30.0       2      0      0         0
213  30.0       2      0      0         0

In [53]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
SibSp        0.00000
Parch        0.00000
Survived     0.00000
dtype: float64

In [54]:
df.dropna(inplace=True)

In [55]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [56]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv = 20))

0.6933333333333332

## Applying Feature Construction

In [57]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [58]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [59]:
def myfunc(num):
    if num == 1:
        return 0
    elif num > 1 and num <= 4:
        return 1
    else :
        return 2

In [60]:
myfunc(8)

2

In [61]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [62]:
X

      Age  Pclass  SibSp  Parch  Family_size  Family_type
0    22.0       3      1      0            2            1
1    38.0       1      1      0            2            1
2    26.0       3      0      0            1            0
3    35.0       1      1      0            2            1
4    35.0       3      0      0            1            0
..    ...     ...    ...    ...          ...          ...
885  39.0       3      0      5            6            2
886  27.0       2      0      0            1            0
887  19.0       1      0      0            1            0
889  26.0       1      0      0            1            0
890  32.0       3      0      0            1            0

[714 rows x 6 columns]

In [63]:
X.drop(columns=['SibSp', 'Parch', 'Family_size'], inplace=True)

In [64]:
X.head(3)

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0

In [65]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring = 'accuracy', cv = 20))

0.7003174603174602

## Feature Splitting

In [66]:
df = pd.read_csv('../__datasets__/train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [67]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [68]:
df['Title'] = df['Name'].str.split(',', expand=True)[1].str.split('.', expand=True)[0]

In [69]:
df['Name'].str.split(',', expand=True)[1].str.split('.', expand=True)

         0                                       1     2
0       Mr                             Owen Harris  None
1      Mrs   John Bradley (Florence Briggs Thayer)  None
2     Miss                                   Laina  None
3      Mrs           Jacques Heath (Lily May Peel)  None
4       Mr                           William Henry  None
..     ...                                     ...   ...
886    Rev                                  Juozas  None
887   Miss                          Margaret Edith  None
888   Miss                Catherine Helen "Carrie"  None
889     Mr                             Karl Howell  None
890     Mr                                 Patrick  None

[891 rows x 3 columns]

In [71]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

Title
 the Countess    1.000000
 Mlle            1.000000
 Sir             1.000000
 Ms              1.000000
 Lady            1.000000
 Mme             1.000000
 Mrs             0.792000
 Miss            0.697802
 Master          0.575000
 Col             0.500000
 Major           0.500000
 Dr              0.428571
 Mr              0.156673
 Jonkheer        0.000000
 Rev             0.000000
 Don             0.000000
 Capt            0.000000
Name: Survived, dtype: float64

In [78]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Is_married
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,0

In [88]:
df['Is_married'] = 0
df.loc[df['Title'] == 'Mrs', 'Is_married'] = 1

In [89]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Is_married
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,0