In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('aug_train.csv')
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36.0,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47.0,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83.0,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52.0,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8.0,0.0

In [3]:
df.shape

(10236, 14)

In [4]:
df.isna().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    2358
relevent_experience          0
enrolled_university        203
education_level            244
major_discipline          1521
experience                  29
company_size              3194
company_type              3269
last_new_job               230
training_hours               1
target                       1
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10236 entries, 0 to 10235
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             10236 non-null  int64
 1   city                    10236 non-null  object
 2   city_development_index  10236 non-null  float64
 3   gender                  7878 non-null   object
 4   relevent_experience     10236 non-null  object
 5   enrolled_university     10033 non-null  object
 6   education_level         9992 non-null   object
 7   major_discipline        8715 non-null   object
 8   experience              10207 non-null  object
 9   company_size            7042 non-null   object
 10  company_type            6967 non-null   object
 11  last_new_job            10006 non-null  object
 12  training_hours          10235 non-null  float64
 13  target                  10235 non-null  float64
dtypes: float64(3), int64(1), object(10)
memory usage: 1.1+ MB

In [9]:
# opening csv from url
import requests
from io import StringIO


url = ""
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

df2 = pd.read_csv(data)

In [14]:
df3 = pd.read_csv('Iris.csv')
df3

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [17]:
df4 = pd.read_csv('MachineLearning.txt', sep = '\t')
df4

    # \*\*\*\*\*\*\*\*\*\*\*\*\* 100 Days of Machine Learning – CampusX \*\*\*\*\*\*\*\*\*\*\*\*\*\*
0                     DAY 1: WHAT IS MACHINE LEARNING?
1                     ================================
2                                            KEY IDEAS
3                                            ---------
4    Machine Learning is about building programs th...
..                                                 ...
152                    1. Helps understand data (EDA).
153  2. Helps choose transformations (log, scaling,...
154  3. Helps interpret model assumptions (e.g., li...
155                              3. Probability basics
156                 4. Event, probability of an event.

[157 rows x 1 columns]

## Index_col parameter

In [21]:
df = pd.read_csv('Iris.csv',index_col = 'Id') 
df.head(1)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
1             5.1           3.5            1.4           0.2  Iris-setosa

## Header parameter

In [23]:
df = pd.read_csv('Iris.csv', header=1)
df.head(2)

   1  5.1  3.5  1.4  0.2  Iris-setosa
0  2  4.9  3.0  1.4  0.2  Iris-setosa
1  3  4.7  3.2  1.3  0.2  Iris-setosa

## use_cols

In [26]:
df = pd.read_csv('Iris.csv', usecols=['SepalLengthCm', 'SepalWidthCm'])
df

     SepalLengthCm  SepalWidthCm
0              5.1           3.5
1              4.9           3.0
2              4.7           3.2
3              4.6           3.1
4              5.0           3.6
..             ...           ...
145            6.7           3.0
146            6.3           2.5
147            6.5           3.0
148            6.2           3.4
149            5.9           3.0

[150 rows x 2 columns]

## Squeeze parameter to get pandas series not df

In [32]:
series = pd.read_csv('Iris.csv', usecols=['Species'])   # optionally pass squeeze=True
series

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

## skip_rows / nrows parameter

In [38]:
df = pd.read_csv('Iris.csv', skiprows=[1,2]) # 0 -> headers
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,3,4.7,3.2,1.3,0.2,Iris-setosa
1,4,4.6,3.1,1.5,0.2,Iris-setosa
2,5,5.0,3.6,1.4,0.2,Iris-setosa
3,6,5.4,3.9,1.7,0.4,Iris-setosa
4,7,4.6,3.4,1.4,0.3,Iris-setosa
...,...,...,...,...,...,...
143,146,6.7,3.0,5.2,2.3,Iris-virginica
144,147,6.3,2.5,5.0,1.9,Iris-virginica
145,148,6.5,3.0,5.2,2.0,Iris-virginica
146,149,6.2,3.4,5.4,2.3,Iris-virginica
147,150,5.9,3.0,5.1,1.8,Iris-virginica

In [40]:
df = pd.read_csv('Iris.csv', nrows=13) 
df

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa

## Encoding Parameter

In [44]:
pd.read_csv('Iris.csv', encoding='latin-1')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

## Skip Bad lines

In [46]:
# pd.read_csv('Iris.csv',sep=';', encoding='latin-1') # error_bad_lines=False

## dtype

In [53]:
pd.read_csv('Iris.csv', dtype={'Id':float}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    float64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(5), object(1)
memory usage: 7.2+ KB

## Handling Dates

In [54]:
# pd.read_csv('file.csv', parse_date=['date']).info()

## Convertors

In [55]:
# run a function which you want to apply on any columns

## na_values

In [56]:
pd.read_csv('Iris.csv', na_values=['Iris-virginica'])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,NaN
146,147,6.3,2.5,5.0,1.9,NaN
147,148,6.5,3.0,5.2,2.0,NaN
148,149,6.2,3.4,5.4,2.3,NaN
149,150,5.9,3.0,5.1,1.8,NaN

## Loading Huge Dataset in small chunks

In [60]:
dfs = pd.read_csv('aug_train.csv', chunksize=2000)

for ch in dfs:
    print(ch.shape)

(2000, 14)
(2000, 14)
(2000, 14)
(2000, 14)
(2000, 14)
(2000, 14)
(2000, 14)
(2000, 14)
(2000, 14)
(1158, 14)